# -*- coding: utf-8 -*-
"""jogo_Par_Impar.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q_ih7G5RGXg6z4yGDESXwfszpjRol2h3
"""



import random
# usuario escolher par ou impar
def par_ou_impar():
  print("====================")
  print("Jogo de par ou ímpar")
  print("0 - Sair")
  print("1 - Impar")
  print("2 - Par")
  print("====================")

# usuario digitar um numero

  while True:
    escolha = int(input("Selecione sua opção e teste sua sorte: " ))
  # programa escolher um numero
    random_number = random.randint(1, 5)

    if escolha == 0:
      print("Obrigado por jogar")
      break
    elif escolha > 2:
      print("Opção inválida")
    else:
      num = int(input("Digite um número de 1 a 5: "))
      soma = num + random_number
      resultado = soma % 2

      print("Número da máquina:", random_number)
      print("Seu número:", num)
      if resultado == 0:
        print("O resultado é Par")
      else:
        print("O resultado é Impar")

      if num <= 5:
        if (escolha == 1 and resultado == 1) or (escolha == 2 and resultado == 0):
          print("Você Ganhou")

        else:
          print("Você Perdeu")

      else:
        print("Número inválido, escolha um número de 1 a 5")

par_ou_impar()